version: "3.7"
services: 
  db:
    image: mysql:5.7
    container_name: mysql-container
    # command: --default-authentication-plugin=mysql_native_password
    command: --init-file /init/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: madeofdust
      MYSQL_DATABASE: my_crud
    volumes: 
      - ./data:/var/lib/mysql
      - ./docker-config/mysql/init.sql:/init/init.sql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
    networks: 
      - mynetwork
  api:
    image: node:15
    container_name: node-container
    ports:
      - "9001:9001"
    networks:
      - mynetwork
    volumes:
      - ./backend:/home/node
      - ./docker-config/node/start_application.sh
    command: /home/node/start_application.sh
    working_dir: /home/node
  web:
    image: nginx
    container_name: nginx-container
    volumes:
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html
    networks:
      - mynetwork
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - db
      - api
networks:
  mynetwork:
    name: mynetwork