version: "3.7"
services: 
  db:
    image: mysql:5.7
    container_name: mysql-container
    command: --init-file /docker-entrypoint-initdb.d/1.sql
      #--default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: madeofdust
    volumes: 
      - ./data:/var/lib/mysql
      - ./docker-config/mysql/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
    restart: always
    networks: 
      - mynetwork
  api:
    image: node
    container_name: node-container
    ports:
      - "9001:9001"
    networks:
      - mynetwork 
networks:
  mynetwork:
    name: mynetwork